org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.22
forge_version_range=[47.3.22,48)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=traincraft
mod_name=Traincraft
mod_license=LGPL-3.0
mod_version=4.4.1_022-port.7.0.4.20.1
mod_group_id=traincraft
mod_authors=Traincraft Team
mod_description=Traincraft port for Minecraft 1.20.1. Adds trains and rolling stock to Minecraft.
